[build]
  base = "/"
  command = "cd video-portfolio && CI=false npm run build"
  publish = "video-portfolio/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 